#!/usr/bin/env python
import subprocess
import sys

if sys.platform == "darwin":
    CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
else:
    raise NotImplementedError(f"Do not know how to find Chrome on {sys.platform}")


def screenshot():
    subprocess.check_call(
        [
            CHROME,
            "--headless",
            "--screenshot=screenshots/overview.png",
            "--window-size=720x320",
            "--hide-scrollbars",
            "out/QuirkyQuest1.html",
        ]
    )


screenshot()
